.TH "Répertoire de référence de include" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Répertoire de référence de include
.SH SYNOPSIS
.br
.PP
.SS "Fichiers"

.in +1c
.ti -1c
.RI "fichier \fBadd_type_vehicule\&.h\fP"
.br
.RI "Les prototypes des fonctions qui enregistrent des nouveaux types de vehicule\&. "
.ti -1c
.RI "fichier \fBadd_vehicule\&.h\fP"
.br
.RI "Les prototypes des fonctions qui enregistrent des nouveaux vehicules\&. "
.ti -1c
.RI "fichier \fBfort\&.h\fP"
.br
.RI "Main header file describing libfort API\&. "
.ti -1c
.RI "fichier \fBhistory\&.h\fP"
.br
.RI "Les prototypes des fonctions qui affichent l'historique des vehicules\&. "
.ti -1c
.RI "fichier \fBlist_types\&.h\fP"
.br
.RI "Les prototypes des fonctions qui affichent la liste des types de vehicules\&. "
.ti -1c
.RI "fichier \fBlist_vehicules\&.h\fP"
.br
.RI "Les prototypes des fonctions qui affichent la liste des vehicules\&. "
.ti -1c
.RI "fichier \fBmain\&.h\fP"
.br
.RI "Les prototypes des fonctions du point d'entrée du programme\&. "
.ti -1c
.RI "fichier \fBsqlite3_client\&.h\fP"
.br
.RI "Le client de test de la connectivite avec la base de donnees et les fonctions communes\&. "
.ti -1c
.RI "fichier \fBunpark_vehicule\&.h\fP"
.br
.RI "Les prototypes des fonctions qui sortent des vehicules du parking\&. "
.in -1c
