.TH "include/add_vehicule.h" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/add_vehicule.h \- Les prototypes des fonctions qui enregistrent des nouveaux vehicules\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3\&.h>\fP
.br
\fC#include 'sqlite3_client\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBadd_vehicule\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "int \fBcount_types\fP"
.br
.ti -1c
.RI "int \fBlast_vehicle_id\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Les prototypes des fonctions qui enregistrent des nouveaux vehicules\&. 


.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuteur\fP
.RS 4
Groupe 10 MBDS/SIGL 
.RE
.PP
\fBDate\fP
.RS 4
25 Avril 2021
.RE
.PP
Contient les prototypes des fonctions du \fBsrc/add_vehicule\&.c\fP 
.SH "Documentation des fonctions"
.PP 
.SS "void add_vehicule ()"

.SH "Documentation des variables"
.PP 
.SS "int count_types"

.SS "int last_vehicle_id"

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
