.TH "src/add_type_vehicule.c" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/add_type_vehicule.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sqlite3\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include '\&.\&./include/sqlite3_client\&.h'\fP
.br
\fC#include '\&.\&./include/add_type_vehicule\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_ADD_TYPE_VEHICULE_\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBadd_type\fP ()"
.br
.RI "Enregistre un nouveau type de vehicule en base de donnees\&. "
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define _ADD_TYPE_VEHICULE_"

.SH "Documentation des fonctions"
.PP 
.SS "void add_type (void)"

.PP
Enregistre un nouveau type de vehicule en base de donnees\&. 
.PP
\fBParamètres\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
void 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
