.TH "include/add_type_vehicule.h" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/add_type_vehicule.h \- Les prototypes des fonctions qui enregistrent des nouveaux types de vehicule\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <sqlite3\&.h>\fP
.br
\fC#include 'sqlite3_client\&.h'\fP
.br

.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBadd_type\fP (void)"
.br
.RI "Enregistre un nouveau type de vehicule en base de donnees\&. "
.in -1c
.SH "Description détaillée"
.PP 
Les prototypes des fonctions qui enregistrent des nouveaux types de vehicule\&. 


.PP
\fBVersion\fP
.RS 4
1\&.0 
.RE
.PP
\fBAuteur\fP
.RS 4
Groupe 10 MBDS/SIGL 
.RE
.PP
\fBDate\fP
.RS 4
25 Avril 2021
.RE
.PP
Contient les prototypes des fonctions du \fBsrc/add_type_vehicule\&.c\fP 
.SH "Documentation des fonctions"
.PP 
.SS "void add_type (void)"

.PP
Enregistre un nouveau type de vehicule en base de donnees\&. 
.PP
\fBParamètres\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
void 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
