.TH "f_cell" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_cell
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBf_string_buffer_t\fP * \fBstr_buffer\fP"
.br
.ti -1c
.RI "enum \fBf_cell_type\fP \fBcell_type\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "enum \fBf_cell_type\fP cell_type"

.SS "\fBf_string_buffer_t\fP* str_buffer"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
