.TH "f_cell_props" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_cell_props
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "size_t \fBcell_row\fP"
.br
.ti -1c
.RI "size_t \fBcell_col\fP"
.br
.ti -1c
.RI "uint32_t \fBproperties_flags\fP"
.br
.ti -1c
.RI "unsigned int \fBcol_min_width\fP"
.br
.ti -1c
.RI "enum \fBft_text_alignment\fP \fBalign\fP"
.br
.ti -1c
.RI "unsigned int \fBcell_padding_top\fP"
.br
.ti -1c
.RI "unsigned int \fBcell_padding_bottom\fP"
.br
.ti -1c
.RI "unsigned int \fBcell_padding_left\fP"
.br
.ti -1c
.RI "unsigned int \fBcell_padding_right\fP"
.br
.ti -1c
.RI "unsigned int \fBcell_empty_string_height\fP"
.br
.ti -1c
.RI "enum \fBft_row_type\fP \fBrow_type\fP"
.br
.ti -1c
.RI "unsigned int \fBcontent_fg_color_number\fP"
.br
.ti -1c
.RI "unsigned int \fBcontent_bg_color_number\fP"
.br
.ti -1c
.RI "unsigned int \fBcell_bg_color_number\fP"
.br
.ti -1c
.RI "enum \fBft_text_style\fP \fBcell_text_style\fP"
.br
.ti -1c
.RI "enum \fBft_text_style\fP \fBcontent_text_style\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "enum \fBft_text_alignment\fP align"

.SS "unsigned int cell_bg_color_number"

.SS "size_t cell_col"

.SS "unsigned int cell_empty_string_height"

.SS "unsigned int cell_padding_bottom"

.SS "unsigned int cell_padding_left"

.SS "unsigned int cell_padding_right"

.SS "unsigned int cell_padding_top"

.SS "size_t cell_row"

.SS "enum \fBft_text_style\fP cell_text_style"

.SS "unsigned int col_min_width"

.SS "unsigned int content_bg_color_number"

.SS "unsigned int content_fg_color_number"

.SS "enum \fBft_text_style\fP content_text_style"

.SS "uint32_t properties_flags"

.SS "enum \fBft_row_type\fP row_type"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
