.TH "f_conv_context" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_conv_context
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBbuf\fP"
.br
.ti -1c
.RI "   wchar_t * \fBwbuf\fP"
.br
.ti -1c
.RI "   const void * \fBu8str\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "size_t \fBraw_avail\fP"
.br
.ti -1c
.RI "struct \fBf_context\fP * \fBcntx\fP"
.br
.ti -1c
.RI "enum \fBf_string_type\fP \fBb_type\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "enum \fBf_string_type\fP b_type"

.SS "char* buf"

.SS "struct \fBf_context\fP* cntx"

.SS "size_t raw_avail"

.SS " u { \&.\&.\&. } union "

.SS "const void* u8str"

.SS "wchar_t* wbuf"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
