.TH "f_context" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_context
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBf_table_properties_t\fP * \fBtable_properties\fP"
.br
.ti -1c
.RI "size_t \fBrow\fP"
.br
.ti -1c
.RI "size_t \fBcolumn\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "size_t column"

.SS "size_t row"

.SS "\fBf_table_properties_t\fP* table_properties"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
