.TH "f_string_buffer" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_string_buffer
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   char * \fBcstr\fP"
.br
.ti -1c
.RI "   wchar_t * \fBwstr\fP"
.br
.ti -1c
.RI "   void * \fBu8str\fP"
.br
.ti -1c
.RI "   void * \fBdata\fP"
.br
.ti -1c
.RI "} \fBstr\fP"
.br
.ti -1c
.RI "size_t \fBdata_sz\fP"
.br
.ti -1c
.RI "enum \fBf_string_type\fP \fBtype\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "char* cstr"

.SS "void* data"

.SS "size_t data_sz"

.SS " str { \&.\&.\&. } union "

.SS "enum \fBf_string_type\fP type"

.SS "void* u8str"

.SS "wchar_t* wstr"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
