.TH "f_table_properties" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
f_table_properties
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "struct \fBfort_border_style\fP \fBborder_style\fP"
.br
.ti -1c
.RI "\fBf_cell_prop_container_t\fP * \fBcell_properties\fP"
.br
.ti -1c
.RI "\fBfort_entire_table_properties_t\fP \fBentire_table_properties\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "struct \fBfort_border_style\fP border_style"

.SS "\fBf_cell_prop_container_t\fP* cell_properties"

.SS "\fBfort_entire_table_properties_t\fP entire_table_properties"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
