.TH "fort_border_style" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fort_border_style
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "const char * \fBborder_chars\fP [\fBBORDER_ITEM_POS_SIZE\fP]"
.br
.ti -1c
.RI "const char * \fBheader_border_chars\fP [\fBBORDER_ITEM_POS_SIZE\fP]"
.br
.ti -1c
.RI "const char * \fBseparator_chars\fP [\fBSEPARATOR_ITEM_POS_SIZE\fP]"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "const char* border_chars[\fBBORDER_ITEM_POS_SIZE\fP]"

.SS "const char* header_border_chars[\fBBORDER_ITEM_POS_SIZE\fP]"

.SS "const char* separator_chars[\fBSEPARATOR_ITEM_POS_SIZE\fP]"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
