.TH "fort_entire_table_properties" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fort_entire_table_properties
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "unsigned int \fBleft_margin\fP"
.br
.ti -1c
.RI "unsigned int \fBtop_margin\fP"
.br
.ti -1c
.RI "unsigned int \fBright_margin\fP"
.br
.ti -1c
.RI "unsigned int \fBbottom_margin\fP"
.br
.ti -1c
.RI "enum \fBft_adding_strategy\fP \fBadd_strategy\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "enum \fBft_adding_strategy\fP add_strategy"

.SS "unsigned int bottom_margin"

.SS "unsigned int left_margin"

.SS "unsigned int right_margin"

.SS "unsigned int top_margin"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
