.TH "ft_border_style" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_border_style
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fort\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "struct \fBft_border_chars\fP \fBborder_chs\fP"
.br
.ti -1c
.RI "struct \fBft_border_chars\fP \fBheader_border_chs\fP"
.br
.ti -1c
.RI "const char * \fBhor_separator_char\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure describing border style\&. 
.SH "Documentation des champs"
.PP 
.SS "struct \fBft_border_chars\fP border_chs"

.SS "struct \fBft_border_chars\fP header_border_chs"

.SS "const char* hor_separator_char"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
