.TH "ft_border_chars" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_border_chars
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fort\&.h>\fP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "const char * \fBtop_border_ch\fP"
.br
.ti -1c
.RI "const char * \fBseparator_ch\fP"
.br
.ti -1c
.RI "const char * \fBbottom_border_ch\fP"
.br
.ti -1c
.RI "const char * \fBside_border_ch\fP"
.br
.ti -1c
.RI "const char * \fBout_intersect_ch\fP"
.br
.ti -1c
.RI "const char * \fBin_intersect_ch\fP"
.br
.in -1c
.SH "Description détaillée"
.PP 
Structure describing border appearance\&. 
.SH "Documentation des champs"
.PP 
.SS "const char* bottom_border_ch"

.SS "const char* in_intersect_ch"

.SS "const char* out_intersect_ch"

.SS "const char* separator_ch"

.SS "const char* side_border_ch"

.SS "const char* top_border_ch"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
