.TH "ft_table" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ft_table
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "\fBf_vector_t\fP * \fBrows\fP"
.br
.ti -1c
.RI "\fBf_table_properties_t\fP * \fBproperties\fP"
.br
.ti -1c
.RI "\fBf_string_buffer_t\fP * \fBconv_buffer\fP"
.br
.ti -1c
.RI "size_t \fBcur_row\fP"
.br
.ti -1c
.RI "size_t \fBcur_col\fP"
.br
.ti -1c
.RI "\fBf_vector_t\fP * \fBseparators\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "\fBf_string_buffer_t\fP* conv_buffer"

.SS "size_t cur_col"

.SS "size_t cur_row"

.SS "\fBf_table_properties_t\fP* properties"

.SS "\fBf_vector_t\fP* rows"

.SS "\fBf_vector_t\fP* separators"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
