.TH "interval" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interval
.SH SYNOPSIS
.br
.PP
.SS "Champs de données"

.in +1c
.ti -1c
.RI "int32_t \fBfirst\fP"
.br
.ti -1c
.RI "int32_t \fBlast\fP"
.br
.in -1c
.SH "Documentation des champs"
.PP 
.SS "int32_t first"

.SS "int32_t last"


.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
