.TH "src/list_vehicules.c" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/list_vehicules.c
.SH SYNOPSIS
.br
.PP
\fC#include <stdlib\&.h>\fP
.br
\fC#include <stdio\&.h>\fP
.br
\fC#include <sqlite3\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include '\&.\&./include/fort\&.h'\fP
.br
\fC#include '\&.\&./include/sqlite3_client\&.h'\fP
.br
\fC#include '\&.\&./include/list_vehicules\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fB_LIST_VEHICULES_\fP"
.br
.in -1c
.SS "Fonctions"

.in +1c
.ti -1c
.RI "void \fBlist_vehicles\fP ()"
.br
.RI "Affiche la liste des vehicules\&. "
.in -1c
.SH "Documentation des macros"
.PP 
.SS "#define _LIST_VEHICULES_"

.SH "Documentation des fonctions"
.PP 
.SS "void list_vehicles ()"

.PP
Affiche la liste des vehicules\&. 
.PP
\fBParamètres\fP
.RS 4
\fIvoid\fP 
.RE
.PP
\fBRenvoie\fP
.RS 4
void 
.RE
.PP

.SH "Auteur"
.PP 
Généré automatiquement par Doxygen pour Park-Man à partir du code source\&.
