.TH "md_readme" 3 "Jeudi 29 Avril 2021" "Version 1.0.0" "Park-Man" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md_readme \- Mini Parking 
Mini Parking en C avec SQLite3, pour le compte du TP3 de classe - Programmation avancee en C
.PP
.SH "Installation"
.PP
.PP
Changer le chemin vers le fichier Database \fCDB_FILE\fP dans \fC\fBsrc/sqlite3_client\&.c\fP\fP
.IP "\(bu" 2
SQLite3 : \fCsudo apt-get install -y sqlite3\fP
.IP "\(bu" 2
libSQLite3-dev \fCsudo apt-get install -y libsqlite3-dev\fP
.PP
.PP
.SH "Compilation"
.PP
.PP
\fCmake app\fP
.PP
.SH "Execution"
.PP
.PP
\fC\&./app\fP 
